### ISSUE TITLE
can we call react-scroll-into-view from another page?

### ISSUE THREAD

**Issue by dhavalveera** [dominikbulaj/react-scroll-into-view#30]
Hello,

I am using Nextjs for building the website, and I will use `react-scroll-into-view` to scroll down to the required specific part of the website.

I've one question if I am using `react-scroll-into-view` for/on Index Page, and if I'm currently on a different page, then if I click on the particular section/part/component of the page of Index, then it'll work?

please help me with this.

**Comment by dominikbulaj** [comment]
Hi,
In your case - being on page A and trying to scroll to an element of page B - it won't work. It only scrolls to the element on the currently rendered page.

**Comment by dhavalveera** [comment]
@dominikbulaj  - can you please help me with how I can achieve this above-mentioned thing? as I don't want to reveal the ID in the URL, I will be grateful to you if you can help me out

**Comment by dominikbulaj** [comment]
@dhavalveera you can use any kind of selector that is valid [CSS Selector](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors) but that element has to be on the page you are viewing. Otherwise, it won't scroll. 
There is no way to request to scroll on the other page (scroll to element on page A while viewing page B), sorry.

**Comment by dhavalveera** [comment]
Okay! got it.

Thanks for your valuable time.
